/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:179e6a55-fdca-4cbb-81f9-463a74a92d0c",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_Z2bt9blCB",
    "aws_user_pools_web_client_id": "7jbuoo2ivb6bu410pgduiiqq08",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://soawsurwkncpxfxn2bqshgdnoy.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-ximslazvhbfpfmdfdutnj7loxi"
};


export default awsmobile;
